version: "3.9"

services:
  db:
    container_name: postgres-spring
    image: postgres:14-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - db
    depends_on:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:

